---
  version: 6.4.0-x86_64

  topic:
    access: access
    daemon: phpdaemon
    jsondaemon: jsondaemon
    javadaemon: javadaemon
    phpdaemon: phpdaemon
    opsdaemon: opsdaemon

  midds_ip:
    - kfk-elk-dev-01.xxlaila.cn
    - kfk-elk-dev-02.xxlaila.cn
    - kfk-elk-dev-03.xxlaila.cn
